FROM wordpress:6.4-apache
RUN echo 'Cache buster: Sat 13 Sep 2025 01:08:39 AM +04'

# Install required packages
RUN apt-get update && apt-get install -y \
    default-mysql-client \
    jq \
    curl \
    unzip \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install AWS CLI v2
RUN curl -L https://github.com/wp-cli/wp-cli/releases/download/v2.8.1/wp-cli-2.8.1.phar -o wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp \
    && /usr/local/bin/wp --info

# Install WP-CLI for WordPress management
RUN curl -L https://github.com/wp-cli/wp-cli/releases/download/v2.8.1/wp-cli-2.8.1.phar -o wp-cli.phar \
    && chmod +x wp-cli.phar \
    && mv wp-cli.phar /usr/local/bin/wp \
    && wp --info || echo "WP-CLI installation failed"


# Download and setup WordPress
RUN cd /tmp && \
    curl -O https://wordpress.org/latest.tar.gz && \
    tar xzf latest.tar.gz && \
    cp -R wordpress/* /var/www/html/ && \
    rm -rf wordpress latest.tar.gz

# Copy application files
COPY wp-config.php /tmp/wp-config.php
COPY docker-entrypoint.sh /usr/local/bin/
COPY wp-content/ /var/www/html/wp-content/


# Install S3 plugin after WordPress installation
RUN cd /tmp && \
    curl -L -o amazon-s3-and-cloudfront.zip https://downloads.wordpress.org/plugin/amazon-s3-and-cloudfront.latest-stable.zip && \
    unzip amazon-s3-and-cloudfront.zip && \
    mv amazon-s3-and-cloudfront /var/www/html/wp-content/plugins/ && \
    rm amazon-s3-and-cloudfront.zip


# Configure Apache to only serve HTTP (disable HTTPS)
RUN echo 'Listen 80' > /etc/apache2/ports.conf && \
    echo 'ServerName localhost' >> /etc/apache2/apache2.conf && \
    a2dismod ssl || true && \
    rm -f /etc/apache2/sites-available/default-ssl.conf && \
    rm -f /etc/apache2/sites-enabled/default-ssl.conf

# Set permissions
RUN chmod +x /usr/local/bin/docker-entrypoint.sh && \
    chown -R www-data:www-data /var/www/html

EXPOSE 80

# use full absolute path for ENTRYPOINT
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["apache2-foreground"]

